openapi: 3.0.0
info:
  description: This is Movie API service.
  version: 1.0.0
  title: Movie App - Test Project
  contact:
    email: sparkin154@gmail.com
servers:
  - url: "http://localhost:8080"
tags:
  - name: movies
    description: Methods to searching movies

paths:
  /movies:
    get:
      tags:
        - movies
        # The tags object allows you to arrange the paths (endpoints) into named groups in the Swagger UI display.
      summary: Get all movies
      description: Fetches a list of movies.
      operationId: getMovies
      parameters:
        - name:
